#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=8
#SBATCH --mem=32G
#SBATCH --time=12:00:00


module load ml-gpu

#This will create the file myfile.txt
ml-gpu /work/LAS/cjquinn-lab/zefuh/selectivity/NeuroX_env/bin/python merge_python_files.py

#This will generate codetest.in and codetest.label
ml-gpu /work/LAS/cjquinn-lab/zefuh/selectivity/NeuroX_env/bin/python POS_dataset_creation.py > logError

#remove observations and labels that have different length
ml-gpu /work/LAS/cjquinn-lab/zefuh/selectivity/NeuroX_env/bin/python skip_lines.py

# remove duplicated lines
ml-gpu /work/LAS/cjquinn-lab/zefuh/selectivity/NeuroX_env/bin/python deduplication.py > log

# validate that activation extraction works without problems
# ml-gpu /work/LAS/cjquinn-lab/zefuh/selectivity/NeuroX_env/bin/python activation_extraction.py > log_validation
