#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=8
#SBATCH --mem=128G
#SBATCH --time=10:00:00
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1

module load ml-gpu
cd 

CUDA_LAUNCH_BLOCKING=1 python run_extraction.py \
    --output_file=dev_activations.json \
    --model_type=auto \
    --config_name=mrm8488/codebert-base-finetuned-detect-insecure-code \
    --tokenizer_name=mrm8488/codebert-base-finetuned-detect-insecure-code \
    --model_name_or_path=mrm8488/codebert-base-finetuned-detect-insecure-code \
    --do_train \
    --data_file=../dataset/train.jsonl \
    --batch_size=32 \
    --layers 0,1,2,3,4,5,6,7,8,9,10,11,12 \
    --sentence_only  \
    --seed 123456  2>&1 | tee dev.log
